'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

type Servico={id:string;nome:string;descricao:string|null;preco:number;duracao_minutos:number}
type Horario={inicio:string;fim:string;hora:string}

export function AgendamentoForm({servicos,dataMinima,dataMaxima}:{servicos:Servico[];dataMinima:string;dataMaxima:string}){
 const router=useRouter(); const [servicoId,setServicoId]=useState(''); const [data,setData]=useState(''); const [horarios,setHorarios]=useState<Horario[]>([]); const [horario,setHorario]=useState<Horario|null>(null); const [nome,setNome]=useState(''); const [telefone,setTelefone]=useState(''); const [observacoes,setObservacoes]=useState(''); const [carregando,setCarregando]=useState(false); const [enviando,setEnviando]=useState(false); const [erro,setErro]=useState('')
 useEffect(()=>{setHorario(null);setHorarios([]);setErro('');if(!servicoId||!data)return;let ativo=true;(async()=>{setCarregando(true);try{const r=await fetch(`/api/disponibilidade?${new URLSearchParams({servico:servicoId,data})}`,{cache:'no-store'});const j=await r.json();if(!ativo)return;if(!r.ok){setErro(j.erro||'Não foi possível consultar os horários.');return}setHorarios(j.horarios||[])}catch{if(ativo)setErro('Não foi possível consultar os horários.')}finally{if(ativo)setCarregando(false)}})();return()=>{ativo=false}},[servicoId,data])
 async function confirmar(e:React.FormEvent){e.preventDefault();if(!servicoId||!horario||!nome||!telefone){setErro('Preencha todos os dados.');return}setEnviando(true);setErro('');try{const r=await fetch('/api/agendamentos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({servico_id:servicoId,inicio:horario.inicio,nome,telefone,observacoes})});const j=await r.json();if(!r.ok){setErro(j.erro||'Não foi possível agendar.');if(r.status===409){setHorario(null);const rr=await fetch(`/api/disponibilidade?${new URLSearchParams({servico:servicoId,data})}`,{cache:'no-store'});const jj=await rr.json();setHorarios(jj.horarios||[])}return}router.push(`/agendamento/${j.agendamento.token}`)}catch{setErro('Não foi possível realizar o agendamento.')}finally{setEnviando(false)}}
 return <form className="stack-lg" onSubmit={confirmar}>
  <section className="card stack"><h2>1. Escolha o serviço</h2>{servicos.map(s=><button key={s.id} type="button" className={`service-choice ${servicoId===s.id?'selected':''}`} onClick={()=>setServicoId(s.id)}><div className="split"><div><strong>{s.nome}</strong>{s.descricao&&<div className="small" style={{opacity:.75,marginTop:5}}>{s.descricao}</div>}</div><div style={{textAlign:'right'}}><strong>{Number(s.preco).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><div className="small" style={{opacity:.75}}>{s.duracao_minutos} min</div></div></div></button>)}</section>
  {servicoId&&<section className="card stack"><h2>2. Escolha a data</h2><input className="input" style={{maxWidth:230}} type="date" min={dataMinima} max={dataMaxima} value={data} onChange={e=>setData(e.target.value)}/></section>}
  {servicoId&&data&&<section className="card stack"><h2>3. Escolha o horário</h2>{carregando?<p className="muted">Carregando horários...</p>:horarios.length===0?<p className="muted">Não há horários disponíveis nesta data.</p>:<div className="times">{horarios.map(h=><button type="button" key={h.inicio} className={`time-choice ${horario?.inicio===h.inicio?'selected':''}`} onClick={()=>setHorario(h)}>{h.hora}</button>)}</div>}</section>}
  {horario&&<section className="card stack"><h2>4. Seus dados</h2><div className="field"><label>Nome</label><input className="input" value={nome} onChange={e=>setNome(e.target.value)} maxLength={120} required/></div><div className="field"><label>WhatsApp</label><input className="input" value={telefone} onChange={e=>setTelefone(e.target.value)} inputMode="tel" placeholder="(75) 99999-9999" required/></div><div className="field"><label>Observações</label><textarea className="textarea" value={observacoes} onChange={e=>setObservacoes(e.target.value)} maxLength={500}/></div></section>}
  {erro&&<div className="notice notice-error">{erro}</div>}
  {horario&&<button className="btn btn-primary btn-block" style={{padding:15}} disabled={enviando}>{enviando?'Confirmando...':'Confirmar agendamento'}</button>}
 </form>
}
