'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
type Horario={inicio:string;fim:string;hora:string}

export function GerenciarAgendamento({token,podeAlterar,dataMinima,dataMaxima}:{token:string;podeAlterar:boolean;dataMinima:string;dataMaxima:string}){
 const router=useRouter();const [modo,setModo]=useState(false);const [data,setData]=useState('');const [horarios,setHorarios]=useState<Horario[]>([]);const [horario,setHorario]=useState<Horario|null>(null);const [carregando,setCarregando]=useState(false);const [erro,setErro]=useState('')
 useEffect(()=>{if(!modo||!data){setHorarios([]);setHorario(null);return}let ativo=true;(async()=>{setCarregando(true);setErro('');try{const r=await fetch(`/api/agendamentos/${token}/disponibilidade?data=${data}`,{cache:'no-store'});const j=await r.json();if(!ativo)return;if(!r.ok){setErro(j.erro||'Falha ao consultar horários.');return}setHorarios(j.horarios||[])}catch{if(ativo)setErro('Falha ao consultar horários.')}finally{if(ativo)setCarregando(false)}})();return()=>{ativo=false}},[modo,data,token])
 async function cancelar(){if(!window.confirm('Deseja realmente cancelar seu agendamento?'))return;setCarregando(true);setErro('');try{const r=await fetch(`/api/agendamentos/${token}/cancelar`,{method:'POST'});const j=await r.json();if(!r.ok){setErro(j.erro||'Não foi possível cancelar.');return}router.refresh()}finally{setCarregando(false)}}
 async function remarcar(){if(!horario)return;setCarregando(true);setErro('');try{const r=await fetch(`/api/agendamentos/${token}/remarcar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inicio:horario.inicio})});const j=await r.json();if(!r.ok){setErro(j.erro||'Não foi possível remarcar.');return}setModo(false);setData('');setHorario(null);router.refresh()}finally{setCarregando(false)}}
 if(!podeAlterar)return <p className="muted small" style={{textAlign:'center',marginTop:20}}>Este agendamento não pode mais ser alterado pelo site.</p>
 return <div className="stack" style={{marginTop:22}}>{erro&&<div className="notice notice-error">{erro}</div>}{!modo?<div className="grid-2"><button className="btn btn-primary" onClick={()=>setModo(true)}>Remarcar</button><button className="btn btn-danger" onClick={cancelar} disabled={carregando}>Cancelar</button></div>:<div className="card-soft stack"><h3>Escolha a nova data</h3><input className="input" style={{maxWidth:230}} type="date" min={dataMinima} max={dataMaxima} value={data} onChange={e=>setData(e.target.value)}/>{carregando&&<p className="muted">Carregando...</p>}{!carregando&&data&&horarios.length===0&&<p className="muted">Nenhum horário disponível.</p>}{horarios.length>0&&<div className="times">{horarios.map(h=><button className={`time-choice ${horario?.inicio===h.inicio?'selected':''}`} type="button" key={h.inicio} onClick={()=>setHorario(h)}>{h.hora}</button>)}</div>}<div className="grid-2"><button className="btn" onClick={()=>setModo(false)}>Voltar</button><button className="btn btn-primary" onClick={remarcar} disabled={!horario||carregando}>Confirmar</button></div></div>}</div>
}
